### ISSUE TITLE
feature request: Loop music in all levels

### ISSUE THREAD

**Issue by milainlambers** [ericlangedijk/Lemmix#1]
It would be nice to have music play whilst playing the new Conway levels.

**Comment by ericlangedijk** [comment]
All levels can (later) add their own music files as well as "borrow" their music from the default styles.
noted!

**Comment by ericlangedijk** [comment]
Not closing of course

**Comment by ericlangedijk** [comment]
In the last release you can add your own music inside custom level folders.
