### ISSUE TITLE
Game controls in pause mode

### ISSUE THREAD

**Issue by MaZuMS** [ericlangedijk/Lemmix#15]
I very much like the pause mode controls in LemmingsPlus II, where you can choose and assign skills by mouse click while keeping the game paused. I also prefer "B" over "P" for stepping back one frame, as "B" is next to "N". 

Great program btw, thanks a lot!!

**Comment by ericlangedijk** [comment]
Good idea and thanks. I will see if this is possible.

**Comment by ericlangedijk** [comment]
Added this in 2.1.0
